= About This Manual

The purpose of this manual is provide necessary info about OpenCPN
development for new and old contributors. It is an updated work
based on the previous manual which still is available in the

https://opencpn.org/wiki/dokuwiki[The OpenCPN dokuwiki site]

The manual is written for readers with basic programming skills.

== Contents

The first section, OpenCPN Development, contains info on how to build
the main program and how to contribute to the OpenCPN project.

The second section, Plugin Development, covers development and
maintenance of plugins. This includes programming info like API and
other interfaces, build setup and plugin deployment.

The Resources section contains various useful resources, notably
on-line NMEA tools.

The Manual Maintenance section does indeed cover how to contribute
to this manual

== Sections Index

We need to have links to the following because the index to the right does not expand when first opened (or we need to fix that!)
Also I think these main heading should have links anyway, and they do not because there is no page or documentation for them.

Indroduction
OpenCPN Development
Plugins Development
Plugin Manager Installer Documentation
Plugin Manual
and several other important links


== Context
This is  one of five manuals available:

* https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:manual_basic[User Manual Basic]
* https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:manual_advanced[User Manual Advanced]
* https://opencpn-manuals.github.io/main/opencpn-plugins/index.html[Plugins Manual]
* https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/intro-AboutThisManual.html[Developer Manual]
* https://opencpn-manuals.github.io/main/opencpn-dev/index.html[Opencpn Programming Manual]

