= About This Manual

The purpose of this manual is provide necessary info about OpenCPN
development for new and old contributors. It is an updated version
of the previous manual which still is available at
https://opencpn.org/wiki/dokuwiki/[The OpenCPN Dokuwiki Site]

The manual is written for readers with basic programming skills.

== Contents

The first section, OpenCPN Development, contains info on how to build
the main program and how to contribute to the OpenCPN project.

The second section, Plugin Development, covers development and
maintenance of plugins. This includes programming info like API and
other interfaces, build setup and plugin deployment.

The Resources section contains various useful resources, notably
on-line NMEA tools.

The Manual Maintenance section does indeed cover how to contribute
to this manual

== Context
This is  one of three manuals available:

* https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual/[User's Manual]
* https://opencpn-manuals.github.io/main/manuals/5.3.1/index.html[User Plugin Manual]
* https://opencpn-manuals.github.io/main/manuals/5.3.1/index.html[Development manual]
