= Compiling on macOS

== OPENCPN - COMPILING FOR MACOS

Revised: 30 December 2021

Setting up a development environment on a Mac, has become a lot easier
over the years. The instructions below describe how to do this. Per 
revised date the instructions worked using these versions:

OSx: Monetery 12.1
Xcode: 13.2.1

Please note that since software continously evolves, these instructions
have to be updated over time as well.

=== CONFIGURE THE BASICS
Update OSx, via System Preferences > Software Update
Install Xcode, via Mac App Store: https://apps.apple.com/us/app/xcode/id497799835
Get and install Packages via http://s.sudre.free.fr/Software.html
Register (for free) at https://developer.apple.com
Install command line tools, via

$ xcode-select --install

Install brew according to https://docs.brew.sh/Installation:

 $ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Check for any issues with:
$ brew doctor

It should return "Your system is ready to brew".

=== BREW REQUIRED PACKAGES
All at once via:

$ brew install cmake gettext tinyxml cairo libexif xz libarchive wxwidgets

Or one by one:

$ brew install cmake
$ brew install gettext
$ brew install tinyxml
$ brew install cairo
$ brew install libexif
$ brew install xz
$ brew install libarchive
$ brew install wxwidgets

Check for any issues with:

$ brew doctor

=== EXTEND PATH AND SET ENVIRONMENT VARIABLES
Open an editor to update ~./bash_profile.
For example with free editor 'atom':

$ atom ~/.bash_profile

If atom is not present, it can be installed via
$ brew install atom

Add the following lines in the bash_profile:

export PATH="/usr/local/opt/gettext/bin:$PATH"
export PATH="/opt/homebrew/opt/libarchive/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/libarchive/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libarchive/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig"
export MACOSX_DEPLOYMENT_TARGET=10.10

=== DOWNLOAD OPENCPN SOURCES 
Feel free to store them anywhere. This instruction uses
the folder ~/sources for that.

 $ mkdir ~/sources
 $ cd ~/sources
 $ git clone https://github.com/OpenCPN/OpenCPN.git

=== CREATE THE BUILD DIRECTORY
The local builds will take place here, so that we don't
work directly in the source tree:

 $ mkdir ~/sources/OpenCPN/build
 $ cd ~/sources/OpenCPN/build

=== AND BUILD
On an Intel Mac you can now create the build files, and build OpenCPN:

 $ cmake ..
 $ make

To build a debug version use:

 $ cmake -DCMAKE_BUILD_TYPE=Debug ..
 $ make



Build and install OpenCPN:

 $ make install

WARNING - Do The Following:

The default install location is (/usr/local/bin). Everything from
/usr/local/bin get's packaged into your DMG which is not desirable. To
avoid this, change the install location with 'cmake' as follows:

 $ cmake -DCMAKE_INSTALL_PREFIX=/Users/dsr/tmp ..

Some developers have reported that the install step copies a redundant
set of the wxWidgets dynamic library into the install directory, causing
OpenCPN to fail. This is intended, but gets annoying for local bundles
not intended to be distributed. A kludgey fix:

 $ sudo rm /usr/local/bin/OpenCPN.app/Contents/MacOS/libwx*dylib

Build the installable DMG:

 $ make create-dmg

Depending on your local system, during both steps above you may observe
insufficient permissions on some files. Either fix the permissions or
use sudo to run make install/create-dmg

To install the application, double-click on the DMG in Finder and drag
OpenCPN.app to the Applications directory.

==== BUILDING PLUGINS (example)

Building Watchdog_pi from dev branch:

Get source code via

 $ cd ~/sources/
 $ git clone git://github.com/seandepagnier/watchdog_pi

And build
 $ mkdir ~/sources/watchdog_pi/build && cd ~/sources/watchdog_pi/build
 $ cmake ..
 $ make
 $ make create-pkg

Double-click on the package in
~/watchdog_pi/build/Watchdog-Plugin-ov50_2.4.pkg This installs into
/Applications/OpenCPN.app

=== EXTRA ACTION FOR APPLE SILICON M1
On an Apple Silicon M1 processor, some extra steps are required
prior to being able to build. These will be described here.


=== OPTIONAL USING XCODE TO BUILD
Alternatively one could use Xcode. Create OpenCPN.xcodeproj via:

 $ cmake -G Xcode ..

Open the file in Xcode, and use the “Build”, “Run”, “Debug”, etc features
as normal. To use the “Run” action you need to bbuild the “OpenCPN” target 
rather than the default “ALL_BUILD” target.
