site:
  title: OpenCPN Developer Manual
  url: https://opencpn-manuals.github.io/development/
  start_page:  ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      edit_url: true

    - url: https://github.com/leamas/opencpn
      branches: manual
      start_path: manual

    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true

    - url: https://github.com/Rasbats/managed_plugins
      branches: main
      start_path: manual

    - url: https://github.com/opencpn-manuals/plugins.git
      branches: main
      edit_url: true
      start_paths:
        - manual/plugins


ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: |
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual
    page-resource_5_url:  https://opencpn-manuals.github.io/main/opencpn-plugins/0.1/index.html
